openapi: 3.0.3
info:
  title: Medical App API
  version: 1.0.0
  description: API for Medical App
paths:
  /api/auth:
    post:
      operationId: auth_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/auth/refresh:
    post:
      operationId: auth_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/v1/institutions/:
    get:
      operationId: v1_institutions_list
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Institution'
          description: ''
    post:
      operationId: v1_institutions_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Institution'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Institution'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Institution'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
          description: ''
  /api/v1/institutions/{id}/:
    get:
      operationId: v1_institutions_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this institution.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
          description: ''
    put:
      operationId: v1_institutions_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this institution.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Institution'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Institution'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Institution'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
          description: ''
    patch:
      operationId: v1_institutions_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this institution.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedInstitution'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedInstitution'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedInstitution'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
          description: ''
    delete:
      operationId: v1_institutions_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this institution.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/users/:
    get:
      operationId: v1_users_list
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
    post:
      operationId: v1_users_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreate'
          description: ''
  /api/v1/users/{id}/:
    get:
      operationId: v1_users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: v1_users_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: v1_users_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    delete:
      operationId: v1_users_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/users/my_profile/:
    get:
      operationId: v1_users_my_profile_retrieve
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSelfUpdate'
          description: ''
  /api/v1/users/update_my_password/:
    patch:
      operationId: v1_users_update_my_password_partial_update
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserUpdatePassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserUpdatePassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserUpdatePassword'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserUpdatePassword'
          description: ''
  /api/v1/users/update_my_profile/:
    patch:
      operationId: v1_users_update_my_profile_partial_update
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserSelfUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserSelfUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserSelfUpdate'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSelfUpdate'
          description: ''
components:
  schemas:
    AccountTypeEnum:
      enum:
      - 1
      - 2
      - 3
      type: integer
    Institution:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        address:
          type: string
          maxLength: 100
        phone_number:
          type: string
          maxLength: 20
        email:
          type: string
          format: email
          maxLength: 254
        is_active:
          type: boolean
          readOnly: true
      required:
      - id
      - is_active
      - name
    PatchedInstitution:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        address:
          type: string
          maxLength: 100
        phone_number:
          type: string
          maxLength: 20
        email:
          type: string
          format: email
          maxLength: 254
        is_active:
          type: boolean
          readOnly: true
    PatchedUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 254
        account_type:
          allOf:
          - $ref: '#/components/schemas/AccountTypeEnum'
          minimum: -2147483648
          maximum: 2147483647
        institutional_id:
          type: string
          maxLength: 20
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        dni:
          type: string
          maxLength: 20
        birth_date:
          type: string
          format: date
          nullable: true
        phone_number:
          type: string
          maxLength: 20
        address:
          type: string
          maxLength: 100
        expiration_date:
          type: string
          format: date
          nullable: true
        is_active:
          type: boolean
          readOnly: true
        is_staff:
          type: boolean
          readOnly: true
        last_active:
          type: string
          format: date-time
          readOnly: true
    PatchedUserSelfUpdate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 254
        account_type:
          allOf:
          - $ref: '#/components/schemas/AccountTypeEnum'
          readOnly: true
        institutional_id:
          type: string
          maxLength: 20
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        dni:
          type: string
          maxLength: 20
        birth_date:
          type: string
          format: date
          nullable: true
        phone_number:
          type: string
          maxLength: 20
        address:
          type: string
          maxLength: 100
        expiration_date:
          type: string
          format: date
          readOnly: true
          nullable: true
        is_active:
          type: boolean
          readOnly: true
        is_staff:
          type: boolean
          readOnly: true
        last_active:
          type: string
          format: date-time
          readOnly: true
    PatchedUserUpdatePassword:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        password:
          type: string
          maxLength: 128
        new_password:
          type: string
          writeOnly: true
    TokenObtainPair:
      type: object
      properties:
        email:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - email
      - password
      - refresh
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 254
        account_type:
          allOf:
          - $ref: '#/components/schemas/AccountTypeEnum'
          minimum: -2147483648
          maximum: 2147483647
        institutional_id:
          type: string
          maxLength: 20
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        dni:
          type: string
          maxLength: 20
        birth_date:
          type: string
          format: date
          nullable: true
        phone_number:
          type: string
          maxLength: 20
        address:
          type: string
          maxLength: 100
        expiration_date:
          type: string
          format: date
          nullable: true
        is_active:
          type: boolean
          readOnly: true
        is_staff:
          type: boolean
          readOnly: true
        last_active:
          type: string
          format: date-time
          readOnly: true
      required:
      - dni
      - email
      - id
      - is_active
      - is_staff
      - last_active
    UserCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 254
        password:
          type: string
          maxLength: 128
        dni:
          type: string
          maxLength: 20
        account_type:
          allOf:
          - $ref: '#/components/schemas/AccountTypeEnum'
          minimum: -2147483648
          maximum: 2147483647
      required:
      - dni
      - email
      - id
      - password
    UserSelfUpdate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 254
        account_type:
          allOf:
          - $ref: '#/components/schemas/AccountTypeEnum'
          readOnly: true
        institutional_id:
          type: string
          maxLength: 20
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        dni:
          type: string
          maxLength: 20
        birth_date:
          type: string
          format: date
          nullable: true
        phone_number:
          type: string
          maxLength: 20
        address:
          type: string
          maxLength: 100
        expiration_date:
          type: string
          format: date
          readOnly: true
          nullable: true
        is_active:
          type: boolean
          readOnly: true
        is_staff:
          type: boolean
          readOnly: true
        last_active:
          type: string
          format: date-time
          readOnly: true
      required:
      - account_type
      - dni
      - email
      - expiration_date
      - id
      - is_active
      - is_staff
      - last_active
    UserUpdatePassword:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        password:
          type: string
          maxLength: 128
        new_password:
          type: string
          writeOnly: true
      required:
      - id
      - new_password
      - password
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
