# Generated by Django 4.1.4 on 2023-02-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dni",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
